### ISSUE TITLE
Hey, thanks!

### ISSUE THREAD

**Issue by parkr** [daniel-beard/TeslaCamViewer#12]
Hey @daniel-beard, just wanted to drop a quick note of thanks for making & open-sourcing this application. It worked great for me to process my videos without having to watch each individual camera's recording at a time. Much appreciated! 🌟

**Comment by daniel-beard** [comment]
You are very welcome! The SwiftUI rewrite should be done soon, it's keyboard shortcut driven and a little easier to use :)

**Comment by parkr** [comment]
That sounds fantastic! Let me know if you'd like me to test something- I can build and give it a go. Cheers!
